// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCnOX03ZAae77zDXeO__tJrktw2te8Bcts",
      authDomain: "e3-app-5c7da.firebaseapp.com",
      databaseURL: "https://e3-app-5c7da-default-rtdb.firebaseio.com",
      projectId: "e3-app-5c7da",
      storageBucket: "e3-app-5c7da.firebasestorage.app",
      messagingSenderId: "709870075014",
      appId: "1:709870075014:web:a979e6e6254d45a239a507",
      measurementId: "G-36J5QX57W1"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZrWaJ_W2aJud1hjlNsT-Q-gPWnH5O1A',
    appId: '1:709870075014:android:e6be88ccd60b501339a507',
    messagingSenderId: '709870075014',
    projectId: 'e3-app-5c7da',
    storageBucket: 'e3-app-5c7da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglsTTnfBkOGZWNOHLUga48NwmIwR2-MM',
    appId: '1:709870075014:ios:87f240235b66e2d939a507',
    messagingSenderId: '709870075014',
    projectId: 'e3-app-5c7da',
    storageBucket: 'e3-app-5c7da.firebasestorage.app',
    iosBundleId: 'com.example.e3App',
  );
}
